on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    strategy:
      matrix:
        node-version: [18.18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn build-storybook

      - name: Remove old artifact (if any)
        continue-on-error: true
        run: |
          gh run artifacts --repo ${{ github.repository }} | grep "storybook-build" && \
          gh run artifacts delete "storybook-build" --repo ${{ github.repository }} --confirm || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: storybook-static
          name: storybook-build # Changed artifact name

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
